server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://172.20.0.8:3306/vmtech?serverTimezone=UTC
    username: root
    password: qwe1212!Q
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

upload:
  dir: /home/centos/upload/

nhn:
  username: bgpyo@naver.com

