server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://172.20.0.8:3306/vmtech?serverTimezone=UTC
    username: root
    password: qwe1212!Q
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  task:
    scheduling:
      pool:
        size: 10


upload:
  dir: /home/centos/upload/


nhn:
  username: bgpyo@naver.com

  mail:
    host: smtp.gmail.com
    username: codejava.net@gmail.com
    password: your_email_password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
