server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vmtech?serverTimezone=UTC
    username: root
    password: cka2tmf#hihi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
#    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  task:
    scheduling:
      pool:
        size: 10
upload:
  dir: /Users/gimjinho/Desktop/upload/

logging:
  level:
    kr.co.specko.masp3d: warn
#    org.hibernate.type.descriptor.sql: trace

AbstractUserDetailsAuthenticationProvider.:
  badCredentials: '아이디 또는 비밀번호를 확인해주세요.'
nhn:
  username: bgpyo@naver.com


